import HeadComplexity.TypicalLogCloseness.MarkedBit

set_option linter.style.header false

/-!
# Statement lock for the marked-bit layer

Every theorem below re-states, verbatim, a target of
`HeadComplexity/TypicalLogCloseness/MarkedBit.lean` and proves it by direct
application of the original.  If any target statement is renamed, weakened,
strengthened, or re-hypothesized, this file stops elaborating and the
campaign audit fails.  DO NOT EDIT THIS FILE (campaign agents: off-limits).
-/

namespace HeadComplexity

open MvPolynomial

theorem frozenMB_sliceAt_cube_eval {m : ℕ} (z : Bool) (y : Fin m → Bool)
    (P : MvPolynomial (Fin (m + 1)) ℝ) :
    eval (cubePoint y) (sliceAt (boolToReal z) P) =
      eval (cubePoint (consBit z y)) P := sliceAt_cube_eval z y P

theorem frozenMB_sliceAt_totalDegree_le {m : ℕ} (t : ℝ)
    (P : MvPolynomial (Fin (m + 1)) ℝ) :
    (sliceAt t P).totalDegree ≤ P.totalDegree := sliceAt_totalDegree_le t P

theorem frozenMB_sliceDiff_totalDegree_le {m d : ℕ} (hd : 1 ≤ d)
    (P : MvPolynomial (Fin (m + 1)) ℝ) (hP : P.totalDegree ≤ d) :
    (sliceAt 1 P - sliceAt 0 P).totalDegree ≤ d - 1 :=
  sliceDiff_totalDegree_le hd P hP

theorem frozenMB_exists_grid_pair {m d : ℕ} (hd : 1 ≤ d) (F : Bool → ℕ → Bool)
    (P : MvPolynomial (Fin (m + 1)) ℝ) (hdeg : P.totalDegree ≤ d)
    (hrep : StrictSignRep P (markedFn F)) :
    ∃ p₀ p₁ : Polynomial ℝ, p₀.natDegree ≤ d ∧ p₁.natDegree ≤ d - 1 ∧
      ∀ (z : Bool) (y : Fin m → Bool),
        (F z (hammingWeight y) = true →
          0 < p₀.eval (hammingWeight y : ℝ) +
            boolToReal z * p₁.eval (hammingWeight y : ℝ)) ∧
        (F z (hammingWeight y) = false →
          p₀.eval (hammingWeight y : ℝ) +
            boolToReal z * p₁.eval (hammingWeight y : ℝ) < 0) :=
  exists_grid_pair hd F P hdeg hrep

theorem frozenMB_coprod_structure (d : ℕ) (h : Fin d) (t : ℝ) :
    (coprod d h t).natDegree = d - 1 ∧ (coprod d h t).Monic ∧
      (coprod d h t).eval (-((h : ℝ) + 1 + 2 * d * t)) ≠ 0 ∧
      ∀ j : Fin d, j ≠ h →
        (coprod d j t).eval (-((h : ℝ) + 1 + 2 * d * t)) = 0 :=
  coprod_structure d h t

theorem frozenMB_exists_coprod_interpolation (d : ℕ) (hd : 1 ≤ d) (t : ℝ)
    (R : Polynomial ℝ) (hR : R.natDegree ≤ d - 1) :
    ∃ cvec : Fin d → ℝ, R = ∑ h, Polynomial.C (cvec h) * coprod d h t :=
  exists_coprod_interpolation d hd t R hR

theorem frozenMB_exists_numerators (d : ℕ) (hd : 1 ≤ d) (p₀ p₁ : Polynomial ℝ)
    (h₀ : p₀.natDegree ≤ d) (h₁ : p₁.natDegree ≤ d - 1) :
    ∃ a μ c : Fin d → ℝ,
      p₀ = ∑ h, (Polynomial.C (a h) + Polynomial.C (μ h) * Polynomial.X) *
        coprod d h 0 ∧
      p₀ + p₁ = ∑ h, (Polynomial.C (a h + c h) + Polynomial.C (μ h) *
        Polynomial.X) * coprod d h 1 :=
  exists_numerators d hd p₀ p₁ h₀ h₁

theorem frozenMB_head_sum_sign (d : ℕ) (hd : 1 ≤ d) (p₀ p₁ : Polynomial ℝ)
    (a μ c : Fin d → ℝ)
    (hid₀ : p₀ = ∑ h, (Polynomial.C (a h) + Polynomial.C (μ h) *
      Polynomial.X) * coprod d h 0)
    (hid₁ : p₀ + p₁ = ∑ h, (Polynomial.C (a h + c h) + Polynomial.C (μ h) *
      Polynomial.X) * coprod d h 1)
    (z : Bool) (k : ℕ) :
    (0 < ∑ h : Fin d, (a h + μ h * k + c h * boolToReal z) /
        ((k : ℝ) + (h : ℝ) + 1 + 2 * d * boolToReal z) ↔
      0 < p₀.eval (k : ℝ) + boolToReal z * p₁.eval (k : ℝ)) :=
  head_sum_sign d hd p₀ p₁ a μ c hid₀ hid₁ z k

theorem frozenMB_markedFn_fracComputable {m d : ℕ} (hd : 1 ≤ d)
    (F : Bool → ℕ → Bool) (hTD : ThresholdDegLE (markedFn (m := m) F) d) :
    fracComputable (m + 1) d (markedFn (m := m) F) :=
  markedFn_fracComputable hd F hTD

theorem frozenMB_HStar_eq_zero_of_thresholdDeg_zero {m : ℕ}
    (F : Bool → ℕ → Bool) (h0 : thresholdDeg (markedFn (m := m) F) = 0) :
    HStar (m + 1) (markedFn (m := m) F) = 0 :=
  HStar_eq_zero_of_thresholdDeg_zero F h0

theorem frozenMB_markedBit_exact {m : ℕ} (F : Bool → ℕ → Bool) :
    thresholdDeg (markedFn (m := m) F) =
        TypicalLogCloseness.RelaxedPOIC2 (m + 1) (markedFn (m := m) F) ∧
      thresholdDeg (markedFn (m := m) F) =
        TypicalLogCloseness.POIC2 (m + 1) (markedFn (m := m) F) ∧
      thresholdDeg (markedFn (m := m) F) =
        HStar (m + 1) (markedFn (m := m) F) := markedBit_exact F

end HeadComplexity
